language: rust

rust:
  - nightly
os:
  - osx
addons:
  apt:
    packages:
      - gcc-multilib
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
install:
  - brew install sdl2 freetype
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
script:
  - travis-cargo build -- --verbose
after_success:
  - touch target/doc/index.html
  - travis-cargo --only nightly doc-upload
