[package]
name = "nTerm"
version = "0.1.0"
authors = [
  "adjivas <adjivas@users.noreply.github.com>",
]
readme = "README.md"
keywords = ["nterm", "terminal", "neko", "term"]
license = "GPL-3.0"

[[bin]]
name = "n-term"
test = false


[features]
default          = []
lints            = ["clippy", "nightly"]
nightly          = [] # for building with nightly and unstable features
unstable         = [] # for building with unstable features on stable Rust
debug            = [] # for building with debug messages
travis           = ["lints", "nightly"] # for building with travis-cargo

[dependencies]
gfx = "0.12"
freetype-rs = "0.11"
gfx_window_glutin = "*"
glutin = "*"

[dependencies.gfx_text]
version          = "*"
default-features = false

[dependencies.pty-proc]
git              = "https://github.com/adjivas/pty-proc.git"
branch           = "tree"

[dependencies.clippy]
version          = "*"
optional         = true
